### ISSUE TITLE
Bundled is only available in English.

### ISSUE THREAD

**Issue by xaviertobin** [xaviertobin/Bundled-Notes-Issue-Feature-Board#1]
When changing the system language on Android applications, the app keeps using English.

**Comment by onipot** [comment]
I'd be available to translate strings in Italian! @xaviertobin 
You could send the strings.xml and I'd edit it :D

**Comment by xaviertobin** [comment]
Thanks, I'll be tackling languages quite soon so I'll get back to you :)

**Comment by dnbnero** [comment]
I can help with Russian

**Comment by NestorRV** [comment]
I can help with Spanish as well!

**Comment by 1nikolas** [comment]
Count me in for Greek

**Comment by GMak9** [comment]
I would like to offer help with the en_us to pt_br translation, if possible.
