### ISSUE TITLE
Allow sign-up/login with email

### ISSUE THREAD

**Issue by rohitkumarj** [xaviertobin/Bundled-Notes-Issue-Feature-Board#10]
I could only see an option to sign-up with Google after downloading the Android app. Privacy policy statement said one should be able to signup with any email (Gmail, Hotmail etc) but I didn't see an option to use anything but Google.

**Comment by xaviertobin** [comment]
The privacy policy states it because the feature is coming very soon :)

**Comment by rohitkumarj** [comment]
Got it, thanks :)

**Comment by GrimamorRATD** [comment]
When you make the "sign in via email" option. Will there be an option to change from Google sign in? Or will you have to export content and create new account (obviously not your Gmail email, haha)
