### ISSUE TITLE
'Mark as Complete' doesn't remove notification

### ISSUE THREAD

**Issue by markbrai** [xaviertobin/Bundled-Notes-Issue-Feature-Board#17]
Not sure if this is a feature or a bug, but selecting 'Mark as complete' on a reminder notification completes the task within the app but the notification itself isn't closed - instead you have to manually 'swipe' the notification away; it would seem logical to close the notification when the task is completed in this way (as most other to-do apps do).

Other than that, very very very impressed with the app! I have been enjoying moving Keep notes over to it over the last few days and am using it as my primary source - have subscribed already! Looking forward to further development of this app!

**Comment by xaviertobin** [comment]
I think this should be the default - the notification should gain a little tick next to it. But yeah, it probably does make sense to just get rid of the notification too.

**Comment by markbrai** [comment]
Hmm....I'm not seeing a tick next to the notification on complete - just to clarify, this is the notification in the Android tray, not anything in the app itself; within the app the tick is displayed. What I am seeing is that if 'mark as complete' in the tray notification is pressed multiple times it toggles the 'complete' status in the app; because it doesn't disappear there is the possibility of the user 'un-completing' it.
