### ISSUE TITLE
ChromeOS Cancel/Save buttons are cut off at the bottom when adding tags

### ISSUE THREAD

**Issue by RobertTalbert** [xaviertobin/Bundled-Notes-Issue-Feature-Board#19]
Here's a screenshot of what I mean. This is the app running on a Pixelbook in a window that is not fullscreen. The Cancel and Save buttons are below the bottom of the window. I can scroll it up to get to the buttons, but they should probably be visible without having to scroll. 

![download](https://user-images.githubusercontent.com/3129186/80287880-09a95c80-8702-11ea-92b7-b8f5dbe41a3d.png)

**Comment by xaviertobin** [comment]
I feel like I gotta get myself a Chromebook!! Thanks. I'll try fix.

**Comment by RobertTalbert** [comment]
I'm a ChromeOS enthusiast, AMA. :)
