### ISSUE TITLE
There's no checklist options in the formatting bar.

### ISSUE THREAD

**Issue by xaviertobin** [xaviertobin/Bundled-Notes-Issue-Feature-Board#2]
The formatting bar includes options for headers etc. but I can't find a way to do a checklist.

**Comment by NestorRV** [comment]
A bullet list and a numbered list entry will be appreciated as well. In terms of how to do it, not sure what you mean, but you can use GitHub formatting bar (when adding a comment to that issue for example) as inspiration:
<img width="691" alt="..." src="https://user-images.githubusercontent.com/14926343/81504174-132cea00-92e8-11ea-9465-6663f20f402d.png">
