### ISSUE TITLE
Make a note checklist for entire format

### ISSUE THREAD

**Issue by zbhoy** [xaviertobin/Bundled-Notes-Issue-Feature-Board#20]
Hi,

I didn't know how to word the title but what I mean is having an option to make a note into a checklist without having to tap the checkbox button on every new line

**Comment by Abdelrhmanwalid** [comment]
I second this, similar to Keep. pretty handy when copying text from other places. 

![keep](https://user-images.githubusercontent.com/7099429/81636678-ba0ea480-9414-11ea-8984-e75a7d1969bf.gif)
