### ISSUE TITLE
Web app looks like this in dark mode

### ISSUE THREAD

**Issue by yonatan8070** [xaviertobin/Bundled-Notes-Issue-Feature-Board#29]
![image](https://user-images.githubusercontent.com/45665471/100888698-1293b500-34bf-11eb-90bc-f1fe890745f7.png)

I don't think I need to say much more...

**Comment by xaviertobin** [comment]
This should be fixed with a hard reload! Apologies, it's a busy time and there are many changes coming to the web app over the next few weeks. A theme bug slipped through!

**Comment by yonatan8070** [comment]
Yup, that fixed it.
