### ISSUE TITLE
Dynamic App Shortcuts for Bundles

### ISSUE THREAD

**Issue by naushadS** [xaviertobin/Bundled-Notes-Issue-Feature-Board#3]
Although i agree, there is an option to pin a bundle shortcut to the homescreen but it takes up multiple shortcuts for multiple bundles. With this feature, one can find the most frequently/recently used bundles by long pressing "Bundled App Icon" on the homescreen. Spotify's Android App has this implemented for recently played songs/albums.

Reference:
[Android Feature Guide](https://developer.android.com/guide/topics/ui/shortcuts)

**Comment by xaviertobin** [comment]
Good idea. Would like to implement Slices too for bundles: https://developer.android.com/guide/slices
