### ISSUE TITLE
Pinned Notifications disappear

### ISSUE THREAD

**Issue by masc-it** [xaviertobin/Bundled-Notes-Issue-Feature-Board#6]
On my Xiaomi Redmi 7 notifications disappear after some time, like 30 minutes or smth. I've disabled all the stupid battery saver stuff and allowed background execution, but it still happens. Could this be a OEM customization problem or a generic one? @xaviertobin

**Comment by xaviertobin** [comment]
It's hard to to tell without seeing the behaviour myself! There are potential ways this can happen, there might even be an invisible crash. I'll keep my eyes peeled for now.

**Comment by onipot** [comment]
> It's hard to to tell without seeing the behaviour myself! There are potential ways this can happen, there might even be an invisible crash. I'll keep my eyes peeled for now.

Sure, I'll try to take a logcat next time
