### ISSUE TITLE
ChromeOS Shelf Cuts Off Bottom of the App

### ISSUE THREAD

**Issue by joebetsill** [xaviertobin/Bundled-Notes-Issue-Feature-Board#7]
I'm not sure if ChromeOS is even something you're looking at, but in case it is, the bottom of the app gets cut off by the "shelf" in ChromeOS. I grabbed a screenshot, below:

![Bundled_ChromeOS_Bottom_Bar](https://user-images.githubusercontent.com/7346727/79773978-27d91c00-8300-11ea-9bf3-3ec17172b1ab.png)

**Comment by xaviertobin** [comment]
I would like to support ChromeOS. I'm assuming this is in full screen, what does it look like when the screen is windowed?

**Comment by joebetsill** [comment]
I don't know how I messed up that reply, but here's what my response should have been;

It looks exactly like when it is run on a phone, even the same proportions, unless I manually resize it. Would a screenshot help?

**Comment by RobertTalbert** [comment]
Sorry to hijack this, but here's a screenshot when the app is windowed: 
![Screenshot 2020-04-25 at 2 23 34 PM - Display 1](https://user-images.githubusercontent.com/3129186/80287618-83d8e180-8700-11ea-939a-a4c0ea622849.png)

So it looks fine there, but OP is correct that when put into fullscreen mode, the shelf cuts it off. A workaround is to auto-hide the shelf, but probably the +Bundle button should just sit higher up in the display.
