### ISSUE TITLE
Time on reminders to be optional

### ISSUE THREAD

**Issue by rohitkumarj** [xaviertobin/Bundled-Notes-Issue-Feature-Board#8]
Thanks for creating Bundled. I can see great potential for it to become a flexible tool to support many productivity systems people have. I have a Todoist based GTD setup but will give Bundled a spin with some projects/areas so that I can help with it's evolution and at some point be able to switch to a subscription. 

First up on the list is to make time optional when setting reminders. This will help schedule action items for a date. Being notified at a particular time is not the objective but to be able to capture a next step or action and slot it away to be handled on a specific day.

**Comment by xaviertobin** [comment]
How would you see this working? Would you still get a notification, or are you suggesting to essentially allow a date to be assigned to a note just for the sake of indicating a time or date?

**Comment by rohitkumarj** [comment]
If there is no time assigned, then there's no need for a notification.

Having a date allows to start seeing what's on the list of to-dos for that
date. For such items a time is not necessary. Making time selection
optional will leave the choice have reminders for specific notes.
