### ISSUE TITLE
View notes with same tag from across Bundles

### ISSUE THREAD

**Issue by rohitkumarj** [xaviertobin/Bundled-Notes-Issue-Feature-Board#9]
Not sure if this is already possible and I have missed it. 
For this to support a productivity system, I should be able to view my ToDos (or say notes with "Next Action" tag) from across Bundles in one view, preferably ordered by due date/time.

**Comment by xaviertobin** [comment]
This is leading me down the path of creating global tags, or at least common tags that can be added to bundles. It's a great idea, but I'm going to take a slower approach with this one and mesh it in with my other thoughts around adding another layer of dimensionality to organising bundles. I have some ideas.

**Comment by rohitkumarj** [comment]
Cool, look forward to having some way to be able to do this. Thanks.
